// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_best_score_of_classic = "CgkIqN-ulPocEAIQAQ"; // <GPGSID>
        public const string achievement_500_stars_in_stage = "CgkIqN-ulPocEAIQBQ"; // <GPGSID>
        public const string achievement_100_stage_clear = "CgkIqN-ulPocEAIQBA"; // <GPGSID>
        public const string leaderboard_cumulative_score_of_100ball = "CgkIqN-ulPocEAIQAg"; // <GPGSID>
        public const string leaderboard_best_score_of_shooting = "CgkIqN-ulPocEAIQCg"; // <GPGSID>
        public const string achievement_reach_10000_score_in_100ball = "CgkIqN-ulPocEAIQBw"; // <GPGSID>
        public const string achievement_first_payment = "CgkIqN-ulPocEAIQBg"; // <GPGSID>
        public const string leaderboard_number_of_stage_clear_stars = "CgkIqN-ulPocEAIQAw"; // <GPGSID>
        public const string achievement_reach_5000_score_in_classic = "CgkIqN-ulPocEAIQCA"; // <GPGSID>

}

